'use strict';
const $=id=>document.getElementById(id),key='ppb-studio-v2';let tasks=[],editing=null;
const number=n=>new Intl.NumberFormat('vi-VN',{maximumFractionDigits:1}).format(n),money=n=>new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND',maximumFractionDigits:0}).format(n);
function notice(text){$('notice').textContent=text;}
try{const raw=localStorage.getItem(key);if(raw)tasks=PPB.validate(JSON.parse(raw));if(localStorage.getItem('ppb-theme')==='dark')document.body.classList.add('dark');}catch{notice('Không đọc được dữ liệu đã lưu. Hãy khôi phục bản sao JSON hoặc kiểm tra quyền lưu trữ trình duyệt.');}
function save(){try{localStorage.setItem(key,JSON.stringify(tasks));notice('Đã lưu trên trình duyệt này.');}catch{notice('Chưa lưu được. Hãy sao lưu JSON trước khi đóng trang.');}render();}
function node(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function render(){const m=PPB.metrics(tasks);$('hours').textContent=number(m.minutes/60)+' giờ';$('value').textContent=money(m.value);$('done').textContent=m.done+' / '+tasks.length;$('payback').textContent=m.payback===null?'Chưa có':number(m.payback)+' tuần';
 const query=$('search').value.toLocaleLowerCase('vi'),priority=$('filter').value,shown=tasks.filter(t=>(t.title+' '+t.category).toLocaleLowerCase('vi').includes(query)&&(priority==='all'||t.priority===priority));
 for(const status of ['todo','doing','done']){const target=$(status==='done'?'completed':status);target.replaceChildren();const group=shown.filter(t=>t.status===status);$('count-'+status).textContent=group.length;for(const t of group){const card=node('article',undefined,'card'),top=node('div');top.append(node('span',({high:'ƯU TIÊN CAO',medium:'ƯU TIÊN VỪA',low:'ƯU TIÊN THẤP'})[t.priority],'tag '+t.priority));card.append(top,node('h4',t.title),node('small',t.category+(t.due?' • Hạn '+t.due.split('-').reverse().join('/') :'')),node('div',number(PPB.weekly(t))+' phút / tuần','saving'),node('small',number(t.before)+' → '+number(t.after)+' phút × '+number(t.frequency)+' lần'));
 const actions=node('div',undefined,'buttons'),select=node('select');select.setAttribute('aria-label','Trạng thái: '+t.title);for(const [v,label]of [['todo','Cần làm'],['doing','Đang làm'],['done','Hoàn thành']]){const o=node('option',label);o.value=v;select.append(o);}select.value=t.status;select.onchange=()=>{t.status=select.value;save();};const edit=node('button','Sửa');edit.onclick=()=>openEditor(t);const del=node('button','Xóa');del.setAttribute('aria-label','Xóa '+t.title);del.onclick=()=>{if(confirm('Xóa “'+t.title+'”? Bạn có thể khôi phục từ bản sao JSON đã xuất.')){tasks=tasks.filter(x=>x.id!==t.id);save();}};actions.append(select,edit,del);card.append(actions);target.append(card);}if(!group.length)target.append(node('p',tasks.length?'Không có công việc phù hợp.':'Thêm công việc để bắt đầu.','empty'));}
 const ranked=[...tasks].sort((a,b)=>PPB.weekly(b)-PPB.weekly(a)).slice(0,5),max=Math.max(1,...ranked.map(t=>Math.abs(PPB.weekly(t))));$('chart').replaceChildren();for(const t of ranked){const row=node('div',undefined,'barrow'),label=node('div',undefined,'barlabel'),track=node('div',undefined,'track'),bar=node('div',undefined,'bar'+(PPB.weekly(t)<0?' negative':''));label.append(node('span',t.title),node('strong',number(PPB.weekly(t))+' phút'));bar.style.width=Math.abs(PPB.weekly(t))/max*100+'%';track.append(bar);row.append(label,track);$('chart').append(row);}if(!ranked.length)$('chart').append(node('p','Chưa có dữ liệu để so sánh.','muted'));
 const best=ranked.find(t=>PPB.weekly(t)>0);$('recommend-title').textContent=best?'Ưu tiên: '+best.title:'Bắt đầu với một việc lặp lại.';$('recommend-text').textContent=best?'Ước tính tiết kiệm '+number(PPB.weekly(best))+' phút mỗi tuần. '+(best.setup>0?'Thời gian triển khai được bù sau khoảng '+number(best.setup/PPB.weekly(best))+' tuần.':'Bạn chưa ghi thời gian triển khai.'):'Thêm số đo trước và sau để biết cải tiến nào đáng đầu tư.';
}
function openEditor(t){editing=t?t.id:null;$('form').reset();$('form-error').textContent='';$('dialog-title').textContent=t?'Sửa công việc':'Thêm công việc';if(t)for(const [k,v]of Object.entries(t)){const field=$('form').elements.namedItem(k);if(field)field.value=v;}$('editor').showModal();}
$('add').onclick=()=>openEditor();$('close').onclick=()=>$('editor').close();$('form').onsubmit=e=>{e.preventDefault();try{const data=Object.fromEntries(new FormData($('form')));for(const k of ['before','after','frequency','setup','rate'])data[k]=Number(data[k]);data.id=editing||('task-'+Date.now()+'-'+Math.random().toString(36).slice(2));const validated=PPB.validate([data])[0];if(editing)tasks=tasks.map(t=>t.id===editing?validated:t);else{if(tasks.length>=1000)throw Error('Tối đa 1.000 công việc.');tasks.push(validated);}$('editor').close();save();}catch(err){$('form-error').textContent=err.message;}};
$('search').oninput=render;$('filter').onchange=render;
$('sample').onclick=()=>{const samples=[['Tổng hợp báo cáo tuần','Vận hành',90,15,1,120,'doing','high'],['Soạn phản hồi khách hàng','Dịch vụ',12,4,15,90,'todo','high'],['Chuẩn hóa tên tài liệu','Tài liệu',30,5,3,45,'done','medium'],['Kiểm tra dữ liệu đầu vào','Dữ liệu',45,20,2,100,'todo','medium']].map((r,i)=>({id:'demo-'+i,title:r[0],category:r[1],before:r[2],after:r[3],frequency:r[4],setup:r[5],status:r[6],priority:r[7],due:'',rate:100000}));const extra=samples.filter(s=>!tasks.some(t=>t.id===s.id));tasks=PPB.validate([...tasks,...extra]);save();notice('Đã thêm dữ liệu minh họa. Các số liệu này không phải kết quả công việc thực tế của bạn.');};
function download(content,type,name){const url=URL.createObjectURL(new Blob([content],{type})),a=node('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('export').onclick=()=>download(JSON.stringify({version:2,exportedAt:new Date().toISOString(),tasks},null,2),'application/json','ppb-studio-backup.json');$('csv').onclick=()=>download(PPB.csv(tasks),'text/csv;charset=utf-8','ppb-bao-cao.csv');$('import').onclick=()=>$('file').click();$('file').onchange=async()=>{const f=$('file').files[0];if(!f)return;try{if(f.size>2000000)throw Error('File quá lớn (tối đa 2 MB).');const data=JSON.parse(await f.text());if(data.version!==2)throw Error('Cần bản sao PPB Studio phiên bản 2.');const imported=PPB.validate(data.tasks);if(confirm('Thay thế '+tasks.length+' công việc hiện tại bằng '+imported.length+' công việc từ bản sao? Hãy sao lưu trước nếu cần.')){tasks=imported;save();notice('Đã khôi phục '+tasks.length+' công việc.');}}catch(err){notice('Không nhập dữ liệu: '+err.message);}$('file').value='';};$('print').onclick=()=>window.print();$('theme').onclick=()=>{document.body.classList.toggle('dark');try{localStorage.setItem('ppb-theme',document.body.classList.contains('dark')?'dark':'light');}catch{}};render();
